Use GitHub Actions
The following changes have been made to the introduction of GitHub Actions.

- Removed .travis.yml. Use GitHub Actions instead of migrating from travis-ci.org to travis-ci.com.
- Introduction of Rakefile. Developers will be able to build with `bundle exec rake` and
maintainers will also be able to release with `bundle exec rake release`.
- Require Ruby 2.3 or higher to prevent the following install error when using `gem i bundler`.

```console
% gem i bundler
ERROR:  Error installing bundler:
        bundler requires Ruby version >= 2.3.0.
```

Currently CI is not working and this PR runs CI.