CI against Ruby 3.2
That's what was changed in Ruby 3.2 to make CI work.

## RSpec 2 has separate job

RSpec 2 has separate job because RSpec 2 doesn't work with Ruby 3.2:

```console
# /opt/hostedtoolcache/Ruby/3.2.1/x64/lib/ruby/gems/3.2.0/gems/rspec-core-2.99.2/lib/rspec/core/ruby_project.rb:27:
in `block in find_first_parent_containing': undefined method `exists?' for File:Class (NoMethodError)
#
#         ascend_until {|path| File.exists?(File.join(path, dir))}
#                                  ^^^^^^^^
# Did you mean?  exist?
#       from /opt/hostedtoolcache/Ruby/3.2.1/x64/lib/ruby/gems/3.2.0/gems/rspec-core-2.99.2/lib/rspec/core/ruby_project.rb:32:
in `block in ascend_until'
#       from /opt/hostedtoolcache/Ruby/3.2.1/x64/lib/ruby/3.2.0/pathname.rb:331:in `ascend'
```

https://github.com/tmm1/test-queue/actions/runs/4443269714/jobs/7800375435

So RSpec 2 is the last version Ruby 3.1 worked on. This PR updates out-of-development RSpec 2 to 2.99.

## `BUNDLE_GEMFILE` specified in run commands as a workaround

And the value of `BUNDLE_GEMFILE: ${{ matrix.gemfile }}` is empty in Ruby 3.2:

```console
Run bundle exec appraisal minitest5 bundle install
 bundle exec appraisal minitest5 bundle install
 shell: /usr/bin/bash -e {0}
 env:
   BUNDLE_GEMFILE:
   TEST_QUEUE_WORKERS: 2
   TEST_QUEUE_VERBOSE: 1
/opt/hostedtoolcache/Ruby/3.2.1/x64/lib/ruby/3.2.0/bundler/resolver.rb:293:
in `raise_not_found!': Could not find gem 'minitest (= 5.4.3)' in locally installed gems. (Bundler::GemNotFound)
```

https://github.com/tmm1/test-queue/actions/runs/4443064205/jobs/7799958894?pr=106

`BUNDLE_GEMFILE=gemfiles/${{ matrix.entry.name }}.gemfile` is specified in run commands as a workaround.